// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-09-12 20:56:33.556556 -0300 -03 m=+0.008612460
package image

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs/action_structs"
	"github.com/kamushadenes/chloe/langchain/actions/functions"
)

type ImageAction struct {
	Name        string
	Description string
	Params *action_structs.ActionParameterSet
	Extra map[string]interface{}
}
// NewImageAction creates a new ImageAction with Params initialized
func NewImageAction() action_structs.Action {
	var params action_structs.ActionParameterSet
	params.AddParam(&action_structs.ActionParameter{
		Name:        "prompt",
		Description: "Prompt to generate",
		Type:        "string",
		Required:    true,
		Enum:        nil,
	})

	return &ImageAction{
		Name:   "image",
		Description: "Generate an image from a prompt",
		Params: &params,
	}
}

// CheckRequiredParams checks if all required params are set
func (a *ImageAction) CheckRequiredParams() error {
	return a.Params.CheckRequiredParams()
}
func (a *ImageAction) GetName() string {
	return a.Name
}
func (a *ImageAction) GetDescription() string {
	return a.Description
}
func (a *ImageAction) SetParam(key, value string) {
	a.Params.SetParam(key, value)
}
func (a *ImageAction) GetParam(key string) (string, error) {
	p, err := a.Params.GetParam(key)
	
	if p == nil {
		return "", fmt.Errorf("param %s not found", key)
	}	

	return p.Value, err
}

func (a *ImageAction) MustGetParam(key string) string {
	v, _ := a.GetParam(key)
	return v
}
func (a *ImageAction) GetParams() []*action_structs.ActionParameter {
	return a.Params.GetParams()
}
func (a *ImageAction) SetMessage(msg *memory.Message) {}
func (a *ImageAction) RunPostActions(request *action_structs.ActionRequest) error {
	return errors.ErrNotImplemented
}

func (a *ImageAction) GetSchema() *functions.FunctionDefinition {
	params := make(map[string]interface{})
	
	params["parameters"] = make(map[string]interface{})
	
	params["parameters"].(map[string]interface{})["type"] = "object"
	params["parameters"].(map[string]interface{})["required"] = []string{}
	
	for k := range a.GetParams() {
		p := a.GetParams()[k]
		params["parameters"].(map[string]interface{})[p.Name] = make(map[string]interface{})	
		
		params["parameters"].(map[string]interface{})[p.Name].(map[string]interface{})["type"] = p.Type
		params["parameters"].(map[string]interface{})[p.Name].(map[string]interface{})["description"] = p.Description
		params["parameters"].(map[string]interface{})[p.Name].(map[string]interface{})["enum"] = p.Enum
		
		if p.Required {
			params["parameters"].(map[string]interface{})["required"] = append(params["parameters"].(map[string]interface{})["required"].([]string), p.Name)
		}
	}

	return &functions.FunctionDefinition{
		Name:        a.GetName(),
		Description: a.GetDescription(),
		Parameters:      a.GetParams(),
	}
}
