// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-06-17 04:59:23.251713 -0300 -03 m=+0.004736667
package mock

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)

// NewMockAction creates a new MockAction with Params initialized
func NewMockAction() structs.Action {
	return &MockAction{
		Name:   "mock",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *MockAction) CheckRequiredParams() error {
	required := []string{
		"foo",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *MockAction) GetName() string {
	return a.Name
}
func (a *MockAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *MockAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *MockAction) GetParams() map[string]string {
	return a.Params
}
func (a *MockAction) SetMessage(msg *memory.Message) {}
