// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.614775 -0300 -03 m=+0.003395043
package wikipedia

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewWikipediaAction creates a new WikipediaAction with Params initialized
func NewWikipediaAction() structs.Action {
	return &WikipediaAction{
		Name:   "wikipedia",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *WikipediaAction) CheckRequiredParams() error {
	required := []string{
		"query",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *WikipediaAction) GetName() string {
	return a.Name
}
func (a *WikipediaAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *WikipediaAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *WikipediaAction) GetParams() map[string]string {
	return a.Params
}
func (a *WikipediaAction) SetMessage(msg *memory.Message) {}
func (a *WikipediaAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
