// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-06-17 04:59:23.251368 -0300 -03 m=+0.004392251
package math

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)

// NewMathAction creates a new MathAction with Params initialized
func NewMathAction() structs.Action {
	return &MathAction{
		Name:   "math",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *MathAction) CheckRequiredParams() error {
	required := []string{
		"expression",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *MathAction) GetName() string {
	return a.Name
}
func (a *MathAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *MathAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *MathAction) GetParams() map[string]string {
	return a.Params
}
func (a *MathAction) SetMessage(msg *memory.Message) {}
func (a *MathAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *MathAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
