// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.612053 -0300 -03 m=+0.000672918
package file

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewAppendFileAction creates a new AppendFileAction with Params initialized
func NewAppendFileAction() structs.Action {
	return &AppendFileAction{
		Name:   "append_file",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *AppendFileAction) CheckRequiredParams() error {
	required := []string{
		"path",
		"content",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *AppendFileAction) GetName() string {
	return a.Name
}
func (a *AppendFileAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *AppendFileAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *AppendFileAction) GetParams() map[string]string {
	return a.Params
}
func (a *AppendFileAction) SetMessage(msg *memory.Message) {}
func (a *AppendFileAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *AppendFileAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
