// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.612751 -0300 -03 m=+0.001370751
package file

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewReadFileAction creates a new ReadFileAction with Params initialized
func NewReadFileAction() structs.Action {
	return &ReadFileAction{
		Name:   "read_file",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *ReadFileAction) CheckRequiredParams() error {
	required := []string{
		"path",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *ReadFileAction) GetName() string {
	return a.Name
}
func (a *ReadFileAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *ReadFileAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *ReadFileAction) GetParams() map[string]string {
	return a.Params
}
func (a *ReadFileAction) SetMessage(msg *memory.Message) {}
func (a *ReadFileAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *ReadFileAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
