// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.61288 -0300 -03 m=+0.001500376
package file

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewWriteFileAction creates a new WriteFileAction with Params initialized
func NewWriteFileAction() structs.Action {
	return &WriteFileAction{
		Name:   "write_file",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *WriteFileAction) CheckRequiredParams() error {
	required := []string{
		"path",
		"content",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *WriteFileAction) GetName() string {
	return a.Name
}
func (a *WriteFileAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *WriteFileAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *WriteFileAction) GetParams() map[string]string {
	return a.Params
}
func (a *WriteFileAction) SetMessage(msg *memory.Message) {}
func (a *WriteFileAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *WriteFileAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
