// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.614114 -0300 -03 m=+0.002733584
package news

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewNewsByCountryAction creates a new NewsByCountryAction with Params initialized
func NewNewsByCountryAction() structs.Action {
	return &NewsByCountryAction{
		Name:   "news_by_country",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *NewsByCountryAction) CheckRequiredParams() error {
	required := []string{
		"query",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *NewsByCountryAction) GetName() string {
	return a.Name
}
func (a *NewsByCountryAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *NewsByCountryAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *NewsByCountryAction) GetParams() map[string]string {
	return a.Params
}
func (a *NewsByCountryAction) SetMessage(msg *memory.Message) {}
func (a *NewsByCountryAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *NewsByCountryAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
