// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-06-17 04:59:23.255276 -0300 -03 m=+0.008300001
package youtube

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)

// NewYoutubeSummarizeAction creates a new YoutubeSummarizeAction with Params initialized
func NewYoutubeSummarizeAction() structs.Action {
	return &YoutubeSummarizeAction{
		Name:   "youtube_summarize",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *YoutubeSummarizeAction) CheckRequiredParams() error {
	required := []string{
		"url",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *YoutubeSummarizeAction) GetName() string {
	return a.Name
}
func (a *YoutubeSummarizeAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *YoutubeSummarizeAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *YoutubeSummarizeAction) GetParams() map[string]string {
	return a.Params
}
func (a *YoutubeSummarizeAction) SetMessage(msg *memory.Message) {}
func (a *YoutubeSummarizeAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *YoutubeSummarizeAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
