// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.615163 -0300 -03 m=+0.003782834
package youtube

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewYoutubeTranscribeAction creates a new YoutubeTranscribeAction with Params initialized
func NewYoutubeTranscribeAction() structs.Action {
	return &YoutubeTranscribeAction{
		Name:   "youtube_transcribe",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *YoutubeTranscribeAction) CheckRequiredParams() error {
	required := []string{
		"url",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *YoutubeTranscribeAction) GetName() string {
	return a.Name
}
func (a *YoutubeTranscribeAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *YoutubeTranscribeAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *YoutubeTranscribeAction) GetParams() map[string]string {
	return a.Params
}
func (a *YoutubeTranscribeAction) SetMessage(msg *memory.Message) {}
func (a *YoutubeTranscribeAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *YoutubeTranscribeAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
