// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-04-07 00:50:33.613331 -0300 -03 m=+0.001951543
package image

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/memory"
	"github.com/kamushadenes/chloe/structs"
)
// NewVariationAction creates a new VariationAction with Params initialized
func NewVariationAction() structs.Action {
	return &VariationAction{
		Name:   "variation",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *VariationAction) CheckRequiredParams() error {
	required := []string{
		"path",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *VariationAction) GetName() string {
	return a.Name
}
func (a *VariationAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *VariationAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *VariationAction) GetParams() map[string]string {
	return a.Params
}
func (a *VariationAction) SetMessage(msg *memory.Message) {}
func (a *VariationAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *VariationAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
