// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2023-06-17 04:59:23.248361 -0300 -03 m=+0.001385167
package file

import (
	"fmt"
	"github.com/kamushadenes/chloe/errors"
	"github.com/kamushadenes/chloe/langchain/memory"
	"github.com/kamushadenes/chloe/structs"
)

// NewDeleteFileAction creates a new DeleteFileAction with Params initialized
func NewDeleteFileAction() structs.Action {
	return &DeleteFileAction{
		Name:   "delete_file",
		Params: make(map[string]string),
	}
}

// CheckRequiredParams checks if all required params are set
func (a *DeleteFileAction) CheckRequiredParams() error {
	required := []string{
		"path",
	}

	for k := range required {
		if _, err := a.GetParam(required[k]); err != nil {
			return errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("required param %s is not set", required[k]))
		}
	}

	return nil
}
func (a *DeleteFileAction) GetName() string {
	return a.Name
}
func (a *DeleteFileAction) SetParam(key, value string) {
	a.Params[key] = value
}
func (a *DeleteFileAction) GetParam(key string) (string, error) {
	if value, ok := a.Params[key]; ok {
		return value, nil
	}

	return "", errors.Wrap(errors.ErrInvalidParameter, fmt.Errorf("param %s not found", key))
}
func (a *DeleteFileAction) GetParams() map[string]string {
	return a.Params
}
func (a *DeleteFileAction) SetMessage(msg *memory.Message) {}
func (a *DeleteFileAction) RunPreActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
func (a *DeleteFileAction) RunPostActions(request *structs.ActionRequest) error {
	return errors.ErrNotImplemented
}
