# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/henrique.goncalves/Dropbox/Projects/Personal/Code/chloe/cmd/chloe
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 198
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 57
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: null
    title: null
    style:
      border: 0px black solid
      boxShadow: none
      margin: 0px
  
  # Add a watermark image to the rendered gifs
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"
  
# Records, feel free to edit them
records:
  - delay: 324
    content: "$ "
  - delay: 100
    content: .
  - delay: 100
    content: /
  - delay: 100
    content: c
  - delay: 100
    content: h
  - delay: 100
    content: l
  - delay: 100
    content: 'oe '
  - delay: 100
    content: c
  - delay: 100
    content: o
  - delay: 100
    content: m
  - delay: 100
    content: p
  - delay: 100
    content: l
  - delay: 100
    content: e
  - delay: 100
    content: t
  - delay: 100
    content: e
  - delay: 491
    content: "\r\n\e[?2004l\r"
  - delay: 18
    content: "Welcome to Chloe CLI\r\nType 'quit' to exit\r\n\r\n\e[1mUser: \e[0m"
  - delay: 608
    content: H
  - delay: 100
    content: e
  - delay: 100
    content: l
  - delay: 100
    content: l
  - delay: 100
    content: o
  - delay: 100
    content: ','
  - delay: 100
    content: ' '
  - delay: 100
    content: C
  - delay: 100
    content: h
  - delay: 100
    content: l
  - delay: 100
    content: o
  - delay: 100
    content: e
  - delay: 100
    content: '!'
  - delay: 100
    content: "\r\n\r\n\e[?25l\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◜\e[0m"
  - delay: 101
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◝\e[0m"
  - delay: 100
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◞\e[0m"
  - delay: 100
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◟\e[0m"
  - delay: 102
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◜\e[0m"
  - delay: 100
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◝\e[0m"
  - delay: 101
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◞\e[0m"
  - delay: 101
    content: "\r\e[K\r\e[36;1mAssistant: \e[0m\e[37m◟\e[0m"
  - delay: 47
    content: "\e[?25h\r\e[K\e[36;1mAssistant: \e[0mHello"
  - delay: 62
    content: ' Hen'
  - delay: 82
    content: rique
  - delay: 61
    content: '!'
  - delay: 83
    content: ' It'
  - delay: 82
    content: '''s'
  - delay: 61
    content: ' really'
  - delay: 58
    content: ' nice'
  - delay: 84
    content: ' to'
  - delay: 86
    content: ' talk'
  - delay: 68
    content: ' to'
  - delay: 70
    content: ' you'
  - delay: 86
    content: ' today'
  - delay: 87
    content: '!'
  - delay: 57
    content: ' How'
  - delay: 71
    content: ' can'
  - delay: 60
    content: ' I'
  - delay: 59
    content: ' assist'
  - delay: 56
    content: ' you'
  - delay: 58
    content: '?'
  - delay: 500
    content: ' '
